-- V10__create_transaccion_eventos_append_only.sql
-- Migración para PHA04TSK22 (Stories 6a-6e, 7 y 9; constitution, principio 2).
--
-- Cada fila registra una transición de transacción. actor_id es nullable para
-- transiciones ejecutadas por jobs del sistema; los actores usuario y admin se
-- refieren a usuarios(id), según la sección "Auditoría de transacciones" de plan.md.
CREATE TABLE transaccion_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id BIGINT NOT NULL CONSTRAINT fk_transaccion_eventos_transaccion REFERENCES transacciones(id),
    actor_id BIGINT CONSTRAINT fk_transaccion_eventos_actor REFERENCES usuarios(id),
    estado_origen VARCHAR(50) NOT NULL,
    estado_destino VARCHAR(50) NOT NULL,
    motivo TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- El historial se consulta por transacción en orden de creación; actor_id se
-- indexa separadamente para la auditoría por responsable definida en plan.md.
CREATE INDEX idx_transaccion_eventos_transaccion_created_at ON transaccion_eventos (transaccion_id, created_at);
CREATE INDEX idx_transaccion_eventos_actor_id ON transaccion_eventos (actor_id);

-- La función y el trigger implementan en PostgreSQL la inmutabilidad requerida
-- por el principio 2. Se usa SQLSTATE 23514 para que JDBC lo traduzca a una
-- DataIntegrityViolationException específica en lugar de una excepción genérica.
CREATE FUNCTION rechazar_modificacion_transaccion_evento()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los eventos de transacción son append-only y no pueden modificarse ni eliminarse'
        USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER trg_transaccion_eventos_append_only
BEFORE UPDATE OR DELETE ON transaccion_eventos
FOR EACH ROW
EXECUTE FUNCTION rechazar_modificacion_transaccion_evento();
