-- V12__create_stripe_refund_outbox.sql
-- Migración para PHA04TSK24 (Story 7; constitution, principio 1).
--
-- La outbox es la orden durable que la cancelación insertará dentro de la misma
-- transacción PostgreSQL que sus efectos locales. payment_intent_id se conserva
-- en la orden para que reintentos posteriores no dependan de una consulta mutable
-- a idempotency_keys. idempotency_key será refund:<transaccion_id> en PHA04TSK07
-- y su unicidad, junto con la de transaccion_id, impide duplicar el reembolso.
CREATE TABLE stripe_refund_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id BIGINT NOT NULL CONSTRAINT uq_stripe_refund_outbox_transaccion UNIQUE
        CONSTRAINT fk_stripe_refund_outbox_transaccion REFERENCES transacciones(id),
    payment_intent_id VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL CONSTRAINT uq_stripe_refund_outbox_idempotency_key UNIQUE,
    estado VARCHAR(20) NOT NULL CONSTRAINT chk_stripe_refund_outbox_estado CHECK (estado IN ('PENDIENTE', 'SOLICITADO')),
    intentos INTEGER NOT NULL DEFAULT 0 CONSTRAINT chk_stripe_refund_outbox_intentos CHECK (intentos >= 0),
    ultimo_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- La outbox es mutable operativamente: el procesador posterior actualiza estado,
-- contador, error y timestamp. El evento canónico de cancelación permanece en
-- transaccion_eventos, cuya inmutabilidad se protege en V10; aquí no se agrega trigger.
