-- V15__create_publicacion_eventos_append_only.sql
-- Migración para PHA06TSK01 (Story 1; constitution, principio 2).
--
-- Cada fila registra canónicamente la creación de una publicación. Las dos
-- referencias son obligatorias porque toda creación tiene publicación y actor.
CREATE TABLE publicacion_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id BIGINT NOT NULL CONSTRAINT fk_publicacion_eventos_publicacion REFERENCES publicaciones(id),
    actor_id BIGINT NOT NULL CONSTRAINT fk_publicacion_eventos_actor REFERENCES usuarios(id),
    tipo VARCHAR(50) NOT NULL CONSTRAINT chk_publicacion_eventos_tipo CHECK (tipo = 'CREADA'),
    detalle TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- La inmutabilidad se aplica en PostgreSQL, no depende de disciplina de la
-- aplicación. SQLSTATE 23514 permite a Spring traducir el rechazo de negocio
-- a DataIntegrityViolationException en vez de una excepción genérica.
CREATE FUNCTION rechazar_modificacion_publicacion_evento()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los eventos de publicación son append-only y no pueden modificarse ni eliminarse'
        USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER trg_publicacion_eventos_append_only
BEFORE UPDATE OR DELETE ON publicacion_eventos
FOR EACH ROW
EXECUTE FUNCTION rechazar_modificacion_publicacion_evento();
