-- V17__create_publicacion_motivos_historicos_append_only.sql
-- Migración para PHA06TSK05 (Story 3; constitution, principios 2 y 3).
--
-- Registra de forma canónica y append-only el motivo literal de cada moderación
-- que mueve una publicación a 'cambios_solicitados' o 'rechazada'. La inserta la
-- capa de moderación (PATCH /publicaciones/{id}/moderar) en la misma transacción
-- que el cambio de estado; la corrección de Story 3 (PATCH /publicaciones/{id}/corregir)
-- nunca la modifica ni la sobrescribe: el motivo previo queda disponible como
-- histórico para consultas futuras (plan.md, "Histórico de motivos de moderación",
-- decisiones de Lino 2026-08-15).
--
-- Decisiones de esquema declaradas:
--   * publicacion_id NULLABLE con ON DELETE SET NULL (mismo patrón que V16): al
--     eliminar una publicación rechazada (PHA06TSK03), el motivo histórico sobrevive
--     con publicacion_id = NULL sin CASCADE, conservando el registro de auditoría.
--   * accion restringida por CHECK al vocabulario de moderación que inserta esta
--     tabla (CAMBIOS_SOLICITADOS / RECHAZADA); APROBADA nunca inserta aquí.
--   * motivo NOT NULL: el dominio ya exige motivo no blanco para esas transiciones
--     (MotivoRequeridoException en PublicacionService.cambiarEstado), por lo que la
--     columna refuerza en el esquema una invariante que la aplicación ya garantiza.
CREATE TABLE publicacion_motivos_historicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id BIGINT CONSTRAINT fk_publicacion_motivos_historicos_publicacion
        REFERENCES publicaciones(id) ON DELETE SET NULL,
    accion VARCHAR(50) NOT NULL CONSTRAINT chk_publicacion_motivos_historicos_accion
        CHECK (accion IN ('CAMBIOS_SOLICITADOS', 'RECHAZADA')),
    motivo TEXT NOT NULL,
    actor_id BIGINT NOT NULL CONSTRAINT fk_publicacion_motivos_historicos_actor
        REFERENCES usuarios(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- La inmutabilidad se aplica en PostgreSQL, no depende de disciplina de la
-- aplicación. SQLSTATE 23514 permite a Spring traducir el rechazo de negocio
-- a DataIntegrityViolationException en vez de una excepción genérica.
--
-- PostgreSQL ejecuta el ON DELETE SET NULL como un UPDATE interno (profundidad
-- de trigger > 1). Se admite exclusivamente esa actualización anidada, limitada
-- a anular publicacion_id; cualquier UPDATE/DELETE directo continúa rechazado.
CREATE FUNCTION rechazar_modificacion_publicacion_motivo_historico()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE'
        AND pg_trigger_depth() > 1
        AND OLD.publicacion_id IS NOT NULL
        AND NEW.publicacion_id IS NULL
        AND OLD.id IS NOT DISTINCT FROM NEW.id
        AND OLD.accion IS NOT DISTINCT FROM NEW.accion
        AND OLD.motivo IS NOT DISTINCT FROM NEW.motivo
        AND OLD.actor_id IS NOT DISTINCT FROM NEW.actor_id
        AND OLD.created_at IS NOT DISTINCT FROM NEW.created_at THEN
        RETURN NEW;
    END IF;

    RAISE EXCEPTION 'Los motivos históricos de moderación son append-only y no pueden modificarse ni eliminarse'
        USING ERRCODE = '23514';
END;
$$;

CREATE TRIGGER trg_publicacion_motivos_historicos_append_only
BEFORE UPDATE OR DELETE ON publicacion_motivos_historicos
FOR EACH ROW
EXECUTE FUNCTION rechazar_modificacion_publicacion_motivo_historico();
