-- V1__init_usuarios_login_attempts.sql
-- Migración inicial para PHA01TSK01: tablas usuarios y login_attempts

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL CONSTRAINT uk_usuarios_email UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL CONSTRAINT chk_usuarios_rol CHECK (rol IN ('USUARIO', 'ADMIN')),
    saldo_disponible BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    intentos INT NOT NULL DEFAULT 0,
    bloqueado_hasta TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_login_attempts_email_ip ON login_attempts (email, ip);
