-- V3__create_admin_acciones.sql
-- Tabla para registro de auditoría append-only de acciones administrativas (Story 0c, plan.md)

CREATE TABLE admin_acciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT NOT NULL CONSTRAINT fk_admin_acciones_admin REFERENCES usuarios(id),
    accion VARCHAR(50) NOT NULL,
    usuario_afectado_id BIGINT CONSTRAINT fk_admin_acciones_usuario_afectado REFERENCES usuarios(id),
    detalle TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_admin_acciones_admin_id ON admin_acciones (admin_id);
CREATE INDEX idx_admin_acciones_usuario_afectado_id ON admin_acciones (usuario_afectado_id);
