-- V4__create_categorias_subcategorias.sql
-- Migración para PHA02TSK01: tablas categorias y subcategorias con constraints de unicidad por nivel jerárquico

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL CONSTRAINT uk_categorias_nombre UNIQUE
);

CREATE TABLE subcategorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT NOT NULL CONSTRAINT fk_subcategorias_categoria REFERENCES categorias(id),
    nombre VARCHAR(255) NOT NULL,
    CONSTRAINT uk_subcategorias_categoria_nombre UNIQUE (categoria_id, nombre)
);

CREATE INDEX idx_subcategorias_categoria_id ON subcategorias (categoria_id);
