-- V5__create_publicaciones.sql
-- Migración para PHA02TSK02: tabla publicaciones con FKs a usuarios, categorias y subcategorias, constraints check de precio/stock/estado y default en estado

CREATE TABLE publicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL CONSTRAINT fk_publicaciones_usuario REFERENCES usuarios(id),
    categoria_id BIGINT NOT NULL CONSTRAINT fk_publicaciones_categoria REFERENCES categorias(id),
    subcategoria_id BIGINT NOT NULL CONSTRAINT fk_publicaciones_subcategoria REFERENCES subcategorias(id),
    precio BIGINT NOT NULL CONSTRAINT chk_publicaciones_precio CHECK (precio > 0),
    stock INTEGER NOT NULL CONSTRAINT chk_publicaciones_stock CHECK (stock >= 0),
    estado VARCHAR(50) NOT NULL DEFAULT 'pendiente_revisión' CONSTRAINT chk_publicaciones_estado CHECK (estado IN ('pendiente_revisión', 'aprobada', 'cambios_solicitados', 'rechazada', 'oculta')),
    descripcion TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_publicaciones_usuario_id ON publicaciones (usuario_id);
CREATE INDEX idx_publicaciones_categoria_id ON publicaciones (categoria_id);
CREATE INDEX idx_publicaciones_subcategoria_id ON publicaciones (subcategoria_id);
CREATE INDEX idx_publicaciones_estado ON publicaciones (estado);
