-- V7__create_transacciones.sql
-- Migración para PHA03TSK01: tabla transacciones con FKs a usuarios (comprador) y publicaciones,
-- snapshot de precio en centavos (entero, principio 3 de constitution), check de estado restringido
-- a los 8 valores exactos de la máquina de estados de transacción (spec.md) y default 'reservada'
-- (spec.md Story 5: la transacción se crea en estado reservada; plan.md: solo existe tras el webhook
-- payment_intent.succeeded, no hay transacción "pendiente de pago").

CREATE TABLE transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(50) NOT NULL DEFAULT 'reservada' CONSTRAINT chk_transacciones_estado CHECK (estado IN ('reservada', 'enviado', 'entregado', 'recibido', 'recibido_sin_respuesta', 'disputa', 'cancelada', 'completada')),
    comprador_id BIGINT NOT NULL CONSTRAINT fk_transacciones_comprador REFERENCES usuarios(id),
    publicacion_id BIGINT NOT NULL CONSTRAINT fk_transacciones_publicacion REFERENCES publicaciones(id),
    precio_snapshot BIGINT NOT NULL CONSTRAINT chk_transacciones_precio_snapshot CHECK (precio_snapshot > 0),
    fecha_reservada TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_enviado TIMESTAMP WITH TIME ZONE,
    fecha_entregado TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_transacciones_comprador_id ON transacciones (comprador_id);
CREATE INDEX idx_transacciones_publicacion_id ON transacciones (publicacion_id);
CREATE INDEX idx_transacciones_estado ON transacciones (estado);
