-- V9__add_transaction_lifecycle_notifications_balance_movements.sql
-- Migración para PHA04TSK01 (Stories 6b, 7, 7b y 12).
--
-- Las columnas de transacciones son TEXT nullable: la Story 6b establece que la
-- descripción de entrega es opcional y el motivo solo se exige al ejecutar la
-- cancelación (Story 7), lógica que corresponde a tareas posteriores.
ALTER TABLE transacciones
    ADD COLUMN descripcion_prueba_entrega TEXT,
    ADD COLUMN motivo_cancelacion TEXT;

-- Plan.md define notificaciones in-app como (usuario_id, mensaje, tipo, leída,
-- timestamp). Se sigue el patrón de V1/V3/V7: PK BIGINT identity, FK nombrada,
-- timestamp TIMESTAMP WITH TIME ZONE y created_at con DEFAULT CURRENT_TIMESTAMP.
-- usuario_id, mensaje y tipo son NOT NULL porque identifican el destinatario y
-- contenido de cada aviso; leida es NOT NULL DEFAULT FALSE para que una fila
-- nueva tenga estado inequívoco sin depender de la futura capa de aplicación.
CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL CONSTRAINT fk_notificaciones_usuario REFERENCES usuarios(id),
    mensaje TEXT NOT NULL,
    tipo VARCHAR(100) NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- La futura consulta GET /notificaciones se limita por usuario y se ordenará por
-- creación; este índice compuesto cubre esa relación sin añadir semántica de negocio.
CREATE INDEX idx_notificaciones_usuario_created_at ON notificaciones (usuario_id, created_at);

-- Plan.md define el ledger append-only como (vendedor_id, transacción_id, monto,
-- timestamp). monto BIGINT conserva centavos enteros (constitución, principio 3).
-- No se agrega una restricción de unicidad ni una semántica de débito/crédito: no
-- están definidas para este esquema y las reglas de creación atómica pertenecen a
-- las tareas de dominio posteriores.
CREATE TABLE movimientos_saldo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id BIGINT NOT NULL CONSTRAINT fk_movimientos_saldo_transaccion REFERENCES transacciones(id),
    vendedor_id BIGINT NOT NULL CONSTRAINT fk_movimientos_saldo_vendedor REFERENCES usuarios(id),
    monto BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Índices de las dos FKs: transaccion_id conserva la trazabilidad por origen y
-- vendedor_id permite consultar el detalle del saldo de un vendedor (Story 12).
CREATE INDEX idx_movimientos_saldo_transaccion_id ON movimientos_saldo (transaccion_id);
CREATE INDEX idx_movimientos_saldo_vendedor_id ON movimientos_saldo (vendedor_id);
